version: "3"
services:
  mysqldb:
    image: mysql/mysql-server:latest
    container_name: surveydb
    ports:
      - 3307:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=SurveyApp
      - MYSQL_USER=evgeny88
      - MYSQL_PASSWORD=Primera77!
    restart: always
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: surveyapp
    ports:
      - 5000:5000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/SurveyApp?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: evgeny88
      DB_PWD: Primera77!
      DB_NAME: SurveyApp
    restart: always
    depends_on: 
      - mysqldb
